### ISSUE TITLE
Wrong account activation link on email

### ISSUE THREAD

**Issue by prakash87** [AusDTO/dto-digitalmarketplace-buyer-frontend#103]
The account activation link on email sends to `dm-buyer-frontend.apps.platform.digital.gov.au/marketplace` instead of `www.gov.au/marketplace`

**Comment by sarneaud** [comment]
Why this is happening: This works okay in the dev environment, but not in live, which is proxied twice.  Flask needs the HTTP Host to be "www.gov.au" to get this URL right, but Cloud Foundry needs the HTTP Host to be "dm-buyer-frontend.apps.platform.digital.gov.au/marketplace" to route requests to the app.  Flask's SERVER_NAME config affects the routing, so it doesn't help.

Flask does recognise the X-Forwarded-Host header, and Cloud Foundry is okay with that, so if we configure the downstream proxy (www.gov.au) to send that header, things should work.

**Comment by sarneaud** [comment]
An X-Forwarded-Host header has been added to the proxy, and I've confirmed that the right URL appears in the email message now.
