### ISSUE TITLE
Filter by role in the Supplier Catalogue is excluding some suppliers that offer that role

### ISSUE THREAD

**Issue by AndrewMatison** [AusDTO/dto-digitalmarketplace-buyer-frontend#166]
When filtering by a role (e.g. Developer), some of the suppliers who offer that role are not listed in the filtered view. 

For the Developer role specifically when tested on 23/Aug, 102 suppliers are shown, however 112 should have been listed.

**Comment by sarneaud** [comment]
The missing results seem to be for suppliers that had a price for a senior developer, but not a junior developer.  I've fixed that issue in the PR above.

**Comment by sarneaud** [comment]
This is live and I'm seeing supplier results that were missing before.
