### ISSUE TITLE
External html links should have an external link icon

### ISSUE THREAD

**Issue by elisechant** [AusDTO/dto-digitalmarketplace-buyer-frontend#221]
For accessibility reasons, ui-kit recommend that external links should open in a new tab and have an external link icon:

<img width="516" alt="screen shot 2016-08-28 at 1 33 54 pm" src="https://cloud.githubusercontent.com/assets/2195815/18031441/25308a4c-6d24-11e6-8d83-7b72db0d1f5b.png">

See https://gov-au-ui-kit.apps.staging.digital.gov.au/section-link-styles.html#guide-link-styles-1-hover-links

**Comment by matt-sm** [comment]
These should now be all fixed.
