### ISSUE TITLE
http site does not enforce upgrade to https

### ISSUE THREAD

**Issue by davecheney** [AusDTO/dto-digitalmarketplace-buyer-frontend#322]
% curl -I http://marketplace.service.gov.au/ 
HTTP/1.1 200 OK
Content-Length: 10265
Content-Type: text/html; charset=utf-8
Date: Sun, 25 Sep 2016 03:22:04 GMT
Dm-Request-Id: e5d2e102-c342-48e6-8d14-3df7d189c8e3
Server: waitress
Set-Cookie: dm_session=eyJfZnJlc2giOmZhbHNlLCJfcGVybWFuZW50Ijp0cnVlfQ.CsjUXA._ibcjEmArabAwCwk51L0fPq3vCI; Expires=Sun, 25-Sep-2016 07:22:04 GMT; Secure; HttpOnly; Path=/
X-Cf-Requestid: d72f9f55-58da-4045-42f8-d362f8f56818
X-Frame-Options: DENY
Connection: keep-alive

/cc @santrancisco

**Comment by matt-sm** [comment]
This has been fixed
