### ISSUE TITLE
Consistency of mapping between model fields and api fields

### ISSUE THREAD

**Issue by djrobstep** [AusDTO/dto-digitalmarketplace-buyer-frontend#368]
Most of the entity models take quite a manual, custom approach to serialization. This results in inevitable mismatch between the model and its serialized form.

This manifests itself most noticeably things like names, which are inclined to drift chinese-whispers style between model, api, and frontend field names.

We could enforce better consistency and clean up some code by doing this is a deterministic manner from the structure of the models. Messy stuff! But probably worth it in the long term.

**Comment by matt-sm** [comment]
Closing for now - we will take a different approach for the next feature we build
