### ISSUE TITLE
Site links to staging ui-kit

### ISSUE THREAD

**Issue by aussielunix** [AusDTO/dto-digitalmarketplace-buyer-frontend#388]
When I visit https://marketplace.service.gov.au
I notice that ui-kit is being loaded from `https://gov-au-ui-kit.apps.staging.digital.gov.au/latest/ui-kit.min.js`

This should be swapped for a production version of the ui-kit.

**Comment by elisechant** [comment]
@aussielunix cdn hosting would be ideal

**Comment by klepas** [comment]
Yes please. I don’t know how to proceed on getting us a CDN though…

**Comment by nathf** [comment]
UI Kit don't currently supply production URLs for their assets, so we will (and should) add this as a hard dependency inside our repo to lock it to the version we are actually on.

**Comment by aussielunix** [comment]
@elisechant @klepas I am not sure how a CDN would help here ?
Can you explain please ?


@nathf thanks.

**Comment by aussielunix** [comment]
uikit are going to have a production url to use soon
https://github.com/AusDTO/gov-au-ui-kit/issues/442

**Comment by klepas** [comment]
> I am not sure how a CDN would help here ?
> Can you explain please ?

Soz Mick, I menat a prod url.

**Comment by matt-sm** [comment]
Planning to upgrade to 2 in near future

**Comment by aussielunix** [comment]
Should this be closed before it is implemented ?

``` bash
[~]
lunix@adaptaur]  -> curl --silent  https://marketplace.service.gov.au/ | grep ui-kit
    <script type="text/javascript" src="https://gov-au-ui-kit.apps.staging.digital.gov.au/latest/ui-kit.min.js"></script>
```
