### ISSUE TITLE
Sign up and login buttons disappear on mobile screens

### ISSUE THREAD

**Issue by ltankey** [AusDTO/dto-digitalmarketplace-buyer-frontend#89]
![image](https://cloud.githubusercontent.com/assets/5369670/17319889/126a85ac-58d4-11e6-8479-906bf4f728db.png)

![image](https://cloud.githubusercontent.com/assets/5369670/17319900/1fed691a-58d4-11e6-8d50-4f339bd76ff3.png)

**Comment by AndrewMatison** [comment]
Thanks for raising. A fix will be in the next minor release.

**Comment by matt-sm** [comment]
This has been fixed
