### ISSUE TITLE
Debug mode is on in user console

### ISSUE THREAD

**Issue by ltankey** [AusDTO/dto-digitalmarketplace-buyer-frontend#91]
<img width="783" alt="screen shot 2016-08-02 at 5 14 07 pm" src="https://cloud.githubusercontent.com/assets/5369670/17319994/93d8da1c-58d4-11e6-99b0-1602fb16de1e.png">

**Comment by elisechant** [comment]
This might be because it checks for "production" as window.location match "gov.uk":
 
<img width="696" alt="screen shot 2016-08-28 at 1 48 09 pm" src="https://cloud.githubusercontent.com/assets/2195815/18031484/264e2194-6d26-11e6-9f2b-ab1a83c4ef32.png">

**Comment by matt-sm** [comment]
Closing for now.  We plan to remove the gov.uk ui-kit in the near future.
